# For REST Resources testing

#******* Event **************
# locally
GET http://localhost:8080/api/v1/event/99/eventId
# Testing "Getting a product with id is out of range" - Works correctly.
#

###

GET http://localhost:8080/api/v1/event/wrong_argument/eventId
# testing a request with an illegal argument - Work correctly
#{
#  "status": 400,
#  "message": "Illegal Argument. Look that you write! For input string: \"wrong_argument\"",
#  "timestamp": 1598958854132
#}

###
# returns ResponseEntity<OutEntity>
GET http://localhost:8080/api/v1/event/serverUnaccepted/first
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityClassSimpleName": "Event",
#  "body": {
#    "actionType": "NO ACTION TYPE",
#    "createdAt": "2020-09-12T12:22:03.891",
#    "entityType": "NO ENTITY TYPE",
#    "serverAcceptedAt": null,
#    "description": "NO DESCRIPTION",
#    "entityId": 0,
#    "id": 0,
#    "title": "NO ENTITY TYPE. NO ACTION TYPE"
#  }
#}
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityClassSimpleName": "Event",
#  "body": {
#    "createdAt": "2020-09-05T08:47:56.396",
#    "entityType": "NullObject",
#    "serverAcceptedAt": "-999999999-01-01T00:00",
#    "description": "",
#    "id": 0,
#    "title": "NullObject Created"
#  }
#}

###
# returns ResponseEntity<OutEntity>
GET http://localhost:8080/api/v1/event/1/eventId
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityClassSimpleName": "Event",
#  "body": {
#    "Order": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityClassSimpleName": "Order",
#      "body": {
#        "delivery": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "Delivery",
#          "body": {
#            "phoneNumber": "+79991234567",
#            "deliveryAddress": {
#              "store": "gb-spring-amin-ishop-heroku",
#              "entityClassSimpleName": "Address",
#              "body": {
#                "country": "Russia",
#                "address": "Секина 99, кв.99",
#                "city": "Королев МО",
#                "id": 3
#              }
#            },
#            "id": 2,
#            "deliveryExpectedAt": "2020-09-05T10:00:00",
#            "order": 3,
#            "deliveryCost": 100.00,
#            "deliveredAt": null
#          }
#        },
#        "createdAt": "2020-09-05T11:26:12",
#        "totalCosts": 5959.00,
#        "orderStatus": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "OrderStatus",
#          "body": {
#            "description": "Принят в работу: Заказ обрабатывается",
#            "id": 2,
#            "title": "Accepted to work"
#          }
#        },
#        "totalItemsCosts": 5859.00,
#        "id": 3,
#        "user": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "User",
#          "body": {
#            "firstName": "f n liyuse",
#            "lastName": "l n liyuse",
#            "phoneNumber": "+79991234567",
#            "deliveryAddress": {
#              "store": "gb-spring-amin-ishop-heroku",
#              "entityClassSimpleName": "Address",
#              "body": {
#                "country": "Russia",
#                "address": "Секина 99, кв.99",
#                "city": "Королев МО",
#                "id": 3
#              }
#            },
#            "id": 2,
#            "userName": "liyuse",
#            "email": "liyuse@ yandex.ru"
#          }
#        },
#        "orderItems": [
#          {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityClassSimpleName": "OrderItem",
#            "body": {
#              "itemCosts": 904.00,
#              "product": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityClassSimpleName": "Product",
#                "body": {
#                  "price": 904.00,
#                  "id": 10,
#                  "shortDescription": "Многофункциональный комплекс Зверье Мое: поточить, поиграть, полежать. Преимущества: - Джут - натуральное текстильное волокно, изготавливаемое из растений одноимённого рода; - серхняя полочка с бортиком, обтянутая премиальным мехом, подарит чудесные минуты отдыха; - пропитка - это наше собственное ноу-хау, неуловимое для человека и притягательное для кошки; - подвесная игрушка не оставит равнодушным питомца; в связи с отзывами о том, что шарик быстро отрывается, подвесную игрушку сделали из джута; - сборка за 20 секунд без инструментов и дополнительных деталей. Когтеточка-столбик \"Зверье Мое\" поможет сохранить мебель и ковры в доме в целостности. Во время царапания кошка выполняет сразу три жизненно важных процесса: стачивает отросшие когти, одновременно затачивая их, метит территорию и выполняет гимнастику тела.",
#                  "category": {
#                    "store": "gb-spring-amin-ishop-heroku",
#                    "entityClassSimpleName": "Category",
#                    "body": {
#                      "id": 7,
#                      "title": "Pets"
#                    }
#                  },
#                  "title": "Зверье Моё / Когтеточка-столбик \"Зверьё Моё\" с полкой, джут, крем-брюле, 40*40*60 см",
#                  "vendorCode": "00000010"
#                }
#              },
#              "quantity": 1,
#              "itemPrice": 904.00,
#              "id": 5,
#              "order": 3
#            }
#          },
#          {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityClassSimpleName": "OrderItem",
#            "body": {
#              "itemCosts": 1958.00,
#              "product": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityClassSimpleName": "Product",
#                "body": {
#                  "price": 979.00,
#                  "id": 9,
#                  "shortDescription": "\"Скорочтение. Как научить ребенка быстро читать\" - переработанное и усовершенствованное переиздание успешного бестселлера по методике скорочтения Ахмадуллина, разделенное на две книги по возрасту для более точечной проработки навыков. Шамиль Ахмадуллин - психолог-педагог, физик, PhD, разработчик более 40 методик эффективного обучения детей. Основатель школ скорочтения и развития памяти у детей. За 18 дней 20-30 минутных занятий Ваш ребенок научится читать в 2 раза быстрее, лучше понимать, запоминать и пересказывать прочитанное. А главное - вы заложите в ребенка один из самых важных навыков 21 века - быстрое усвоение любой текстовой информации. Это даст ребенку огромные преимущества во взрослой жизни! Книга-тренинг для младших школьников: 18-дневный тренинг; более 100 заданий; улучшение внимания; повысится успеваемость в школе; ребенок научится пересказывать; тренировка памяти; формирование навыка быстрого чтения; занятия по 30 минут в день.",
#                  "category": {
#                    "store": "gb-spring-amin-ishop-heroku",
#                    "entityClassSimpleName": "Category",
#                    "body": {
#                      "id": 6,
#                      "title": "Книги"
#                    }
#                  },
#                  "title": "Филипок и Ко / Скорочтение для детей от 6 до 9 лет.",
#                  "vendorCode": "00000009"
#                }
#              },
#              "quantity": 2,
#              "itemPrice": 979.00,
#              "id": 6,
#              "order": 3
#            }
#          },
#          {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityClassSimpleName": "OrderItem",
#            "body": {
#              "itemCosts": 2997.00,
#              "product": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityClassSimpleName": "Product",
#                "body": {
#                  "price": 999.00,
#                  "id": 11,
#                  "shortDescription": "Размер на модели: S. *Параметры в описании указаны для размера: S.",
#                  "category": {
#                    "store": "gb-spring-amin-ishop-heroku",
#                    "entityClassSimpleName": "Category",
#                    "body": {
#                      "id": 5,
#                      "title": "Одежда"
#                    }
#                  },
#                  "title": "ТВОЕ / Платье",
#                  "vendorCode": "00000011"
#                }
#              },
#              "quantity": 3,
#              "itemPrice": 999.00,
#              "id": 7,
#              "order": 3
#            }
#          }
#        ],
#        "updatedAt": "2020-09-05T13:09:08"
#      }
#    },
#    "actionType": "ORDER_STATUS_CHANGED",
#    "createdAt": "2020-09-05T13:09:09",
#    "entityType": "Order",
#    "serverAcceptedAt": "2020-09-04T06:24:33",
#    "description": "Order has been ORDER_STATUS_CHANGED",
#    "entityId": 3,
#    "id": 1,
#    "title": "Order ORDER_STATUS_CHANGED"
#  }
#}

###

PUT http://localhost:8080/api/v1/event/16/eventId/serverAcceptedAt
Content-Type: application/json

"2020-09-04T06:24:32.773"
###
#{
#  "id": null,
#  "actionType": null,
#  "title": null,
#  "description": null,
#  "entityType": null,
#  "entityId": null,
#  "createdAt": null,
#  "serverAcceptedAt": "2020-09-04T06:24:32.773"
#}
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityClassSimpleName": "Event",
#  "body": {
#    "Order": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityClassSimpleName": "Order",
#      "body": {
#        "delivery": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "Delivery",
#          "body": {
#            "phoneNumber": "+79991234567",
#            "deliveryAddress": {
#              "store": "gb-spring-amin-ishop-heroku",
#              "entityClassSimpleName": "Address",
#              "body": {
#                "country": "Russia",
#                "address": "Секина 99, кв.99",
#                "city": "Королев МО",
#                "id": 3
#              }
#            },
#            "id": 1,
#            "deliveryExpectedAt": "2020-09-05T10:00:00",
#            "order": 2,
#            "deliveryCost": 100.00,
#            "deliveredAt": null
#          }
#        },
#        "createdAt": "2020-09-05T11:24:47",
#        "totalCosts": 3057.00,
#        "orderStatus": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "OrderStatus",
#          "body": {
#            "description": "Доставлен: Заказ получен пользователем",
#            "id": 5,
#            "title": "Delivered"
#          }
#        },
#        "totalItemsCosts": 2957.00,
#        "id": 2,
#        "user": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityClassSimpleName": "User",
#          "body": {
#            "firstName": "f n liyuse",
#            "lastName": "l n liyuse",
#            "phoneNumber": "+79991234567",
#            "deliveryAddress": {
#              "store": "gb-spring-amin-ishop-heroku",
#              "entityClassSimpleName": "Address",
#              "body": {
#                "country": "Russia",
#                "address": "Секина 99, кв.99",
#                "city": "Королев МО",
#                "id": 3
#              }
#            },
#            "id": 2,
#            "userName": "liyuse",
#            "email": "liyuse@ yandex.ru"
#          }
#        },
#        "orderItems": [
#          {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityClassSimpleName": "OrderItem",
#            "body": {
#              "itemCosts": 1958.00,
#              "product": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityClassSimpleName": "Product",
#                "body": {
#                  "price": 979.00,
#                  "id": 9,
#                  "shortDescription": "\"Скорочтение. Как научить ребенка быстро читать\" - переработанное и усовершенствованное переиздание успешного бестселлера по методике скорочтения Ахмадуллина, разделенное на две книги по возрасту для более точечной проработки навыков. Шамиль Ахмадуллин - психолог-педагог, физик, PhD, разработчик более 40 методик эффективного обучения детей. Основатель школ скорочтения и развития памяти у детей. За 18 дней 20-30 минутных занятий Ваш ребенок научится читать в 2 раза быстрее, лучше понимать, запоминать и пересказывать прочитанное. А главное - вы заложите в ребенка один из самых важных навыков 21 века - быстрое усвоение любой текстовой информации. Это даст ребенку огромные преимущества во взрослой жизни! Книга-тренинг для младших школьников: 18-дневный тренинг; более 100 заданий; улучшение внимания; повысится успеваемость в школе; ребенок научится пересказывать; тренировка памяти; формирование навыка быстрого чтения; занятия по 30 минут в день.",
#                  "category": {
#                    "store": "gb-spring-amin-ishop-heroku",
#                    "entityClassSimpleName": "Category",
#                    "body": {
#                      "id": 6,
#                      "title": "Книги"
#                    }
#                  },
#                  "title": "Филипок и Ко / Скорочтение для детей от 6 до 9 лет.",
#                  "vendorCode": "00000009"
#                }
#              },
#              "quantity": 2,
#              "itemPrice": 979.00,
#              "id": 3,
#              "order": 2
#            }
#          },
#          {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityClassSimpleName": "OrderItem",
#            "body": {
#              "itemCosts": 999.00,
#              "product": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityClassSimpleName": "Product",
#                "body": {
#                  "price": 999.00,
#                  "id": 11,
#                  "shortDescription": "Размер на модели: S. *Параметры в описании указаны для размера: S.",
#                  "category": {
#                    "store": "gb-spring-amin-ishop-heroku",
#                    "entityClassSimpleName": "Category",
#                    "body": {
#                      "id": 5,
#                      "title": "Одежда"
#                    }
#                  },
#                  "title": "ТВОЕ / Платье",
#                  "vendorCode": "00000011"
#                }
#              },
#              "quantity": 1,
#              "itemPrice": 999.00,
#              "id": 4,
#              "order": 2
#            }
#          }
#        ],
#        "updatedAt": "2020-09-05T12:47:10"
#      }
#    },
#    "createdAt": "2020-09-05T12:47:10",
#    "entityType": "Order",
#    "serverAcceptedAt": "2020-09-04T06:24:32.773",
#    "description": "Order has been ORDER_STATUS_CHANGED",
#    "id": 6,
#    "title": "Order ORDER_STATUS_CHANGED"
#  }
#}


###

POST http://localhost:8080/api/v1/event/save/incoming/string
Content-Type: application/json

{
  "store": "gb-spring-amin-ishop-heroku",
  "entityClassSimpleName": "Event",
  "body": {
    "Order": {
      "store": "gb-spring-amin-ishop-heroku",
      "entityClassSimpleName": "Order",
      "body": {
        "delivery": {
          "store": "gb-spring-amin-ishop-heroku",
          "entityClassSimpleName": "Delivery",
          "body": {
            "phoneNumber": "+79991234567",
            "deliveryAddress": {
              "store": "gb-spring-amin-ishop-heroku",
              "entityClassSimpleName": "Address",
              "body": {
                "country": "Russia",
                "address": "Секина 99, кв.99",
                "city": "Королев МО",
                "id": 3
              }
            },
            "id": 2,
            "deliveryExpectedAt": "2020-09-05T10:00:00",
            "order": 3,
            "deliveryCost": 100.00,
            "deliveredAt": null
          }
        },
        "createdAt": "2020-09-05T11:26:12",
        "totalCosts": 5959.00,
        "orderStatus": {
          "store": "gb-spring-amin-ishop-heroku",
          "entityClassSimpleName": "OrderStatus",
          "body": {
            "description": "Принят в работу: Заказ обрабатывается",
            "id": 2,
            "title": "Accepted to work"
          }
        },
        "totalItemsCosts": 5859.00,
        "id": 3,
        "user": {
          "store": "gb-spring-amin-ishop-heroku",
          "entityClassSimpleName": "User",
          "body": {
            "firstName": "f n liyuse",
            "lastName": "l n liyuse",
            "phoneNumber": "+79991234567",
            "deliveryAddress": {
              "store": "gb-spring-amin-ishop-heroku",
              "entityClassSimpleName": "Address",
              "body": {
                "country": "Russia",
                "address": "Секина 99, кв.99",
                "city": "Королев МО",
                "id": 3
              }
            },
            "id": 2,
            "userName": "liyuse",
            "email": "liyuse@yandex.ru"
          }
        },
        "orderItems": [
          {
            "store": "gb-spring-amin-ishop-heroku",
            "entityClassSimpleName": "OrderItem",
            "body": {
              "itemCosts": 904.00,
              "product": {
                "store": "gb-spring-amin-ishop-heroku",
                "entityClassSimpleName": "Product",
                "body": {
                  "price": 904.00,
                  "id": 10,
                  "shortDescription": "Многофункциональный комплекс Зверье Мое: поточить, поиграть, полежать. Преимущества: - Джут - натуральное текстильное волокно, изготавливаемое из растений одноимённого рода; - серхняя полочка с бортиком, обтянутая премиальным мехом, подарит чудесные минуты отдыха; - пропитка - это наше собственное ноу-хау, неуловимое для человека и притягательное для кошки; - подвесная игрушка не оставит равнодушным питомца; в связи с отзывами о том, что шарик быстро отрывается, подвесную игрушку сделали из джута; - сборка за 20 секунд без инструментов и дополнительных деталей. Когтеточка-столбик \"Зверье Мое\" поможет сохранить мебель и ковры в доме в целостности. Во время царапания кошка выполняет сразу три жизненно важных процесса: стачивает отросшие когти, одновременно затачивая их, метит территорию и выполняет гимнастику тела.",
                  "category": {
                    "store": "gb-spring-amin-ishop-heroku",
                    "entityClassSimpleName": "Category",
                    "body": {
                      "id": 7,
                      "title": "Pets"
                    }
                  },
                  "title": "Зверье Моё / Когтеточка-столбик \"Зверьё Моё\" с полкой, джут, крем-брюле, 40*40*60 см",
                  "vendorCode": "00000010"
                }
              },
              "quantity": 1,
              "itemPrice": 904.00,
              "id": 5,
              "order": 3
            }
          },
          {
            "store": "gb-spring-amin-ishop-heroku",
            "entityClassSimpleName": "OrderItem",
            "body": {
              "itemCosts": 1958.00,
              "product": {
                "store": "gb-spring-amin-ishop-heroku",
                "entityClassSimpleName": "Product",
                "body": {
                  "price": 979.00,
                  "id": 9,
                  "shortDescription": "\"Скорочтение. Как научить ребенка быстро читать\" - переработанное и усовершенствованное переиздание успешного бестселлера по методике скорочтения Ахмадуллина, разделенное на две книги по возрасту для более точечной проработки навыков. Шамиль Ахмадуллин - психолог-педагог, физик, PhD, разработчик более 40 методик эффективного обучения детей. Основатель школ скорочтения и развития памяти у детей. За 18 дней 20-30 минутных занятий Ваш ребенок научится читать в 2 раза быстрее, лучше понимать, запоминать и пересказывать прочитанное. А главное - вы заложите в ребенка один из самых важных навыков 21 века - быстрое усвоение любой текстовой информации. Это даст ребенку огромные преимущества во взрослой жизни! Книга-тренинг для младших школьников: 18-дневный тренинг; более 100 заданий; улучшение внимания; повысится успеваемость в школе; ребенок научится пересказывать; тренировка памяти; формирование навыка быстрого чтения; занятия по 30 минут в день.",
                  "category": {
                    "store": "gb-spring-amin-ishop-heroku",
                    "entityClassSimpleName": "Category",
                    "body": {
                      "id": 6,
                      "title": "Книги"
                    }
                  },
                  "title": "Филипок и Ко / Скорочтение для детей от 6 до 9 лет.",
                  "vendorCode": "00000009"
                }
              },
              "quantity": 2,
              "itemPrice": 979.00,
              "id": 6,
              "order": 3
            }
          },
          {
            "store": "gb-spring-amin-ishop-heroku",
            "entityClassSimpleName": "OrderItem",
            "body": {
              "itemCosts": 2997.00,
              "product": {
                "store": "gb-spring-amin-ishop-heroku",
                "entityClassSimpleName": "Product",
                "body": {
                  "price": 999.00,
                  "id": 11,
                  "shortDescription": "Размер на модели: S. *Параметры в описании указаны для размера: S.",
                  "category": {
                    "store": "gb-spring-amin-ishop-heroku",
                    "entityClassSimpleName": "Category",
                    "body": {
                      "id": 5,
                      "title": "Одежда"
                    }
                  },
                  "title": "ТВОЕ / Платье",
                  "vendorCode": "00000011"
                }
              },
              "quantity": 3,
              "itemPrice": 999.00,
              "id": 7,
              "order": 3
            }
          }
        ],
        "updatedAt": "2020-09-05T13:09:08"
      }
    },
    "actionType": "ORDER_STATUS_CHANGED",
    "createdAt": "2020-09-05T13:09:09",
    "entityType": "Order",
    "serverAcceptedAt": "2020-09-06T06:24:33",
    "description": "Order has been ORDER_STATUS_CHANGED",
    "entityId": 3,
    "id": 1,
    "title": "Order ORDER_STATUS_CHANGED"
  }
}
###
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityClassSimpleName": "Event",
#  "body": {
#    "actionType": "Incoming",
#    "createdAt": "2020-09-11T16:59:19.013",
#    "entityType": "Event",
#    "serverAcceptedAt": null,
#    "description": "Event has been Incoming",
#    "entityId": 1,
#    "id": 20,
#    "title": "Event Incoming"
#  }
#}