# For REST Resources testing

#******* User **************
###
# HEROKU
#********* App for Developing Stage *********
###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/user/99/userId
## testing not existing user by out of range id - Works correctly!
#

###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/user/wrong_argument/userId
# testing a request with an illegal argument - Work correctlly!
#

###
# returns ResponseEntity<OutEntity>
GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/user/1/userId
# getting a user by id - Works correctly!
#