# For REST Resources testing

#******* Product **************
###
# HEROKU
#********* App for Developing Stage *********
###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/product/99/productId
## testing not existing product by out of range id - Works correctly!
#

###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/product/wrong_argument/productId
# testing a request with an illegal argument - Work correctlly!
#

###
# returns ResponseEntity<OutEntity>
GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/product/2/productId
# getting a product by id - Works correctly!
#