# For REST Resources testing

#******* Product **************

GET http://localhost:8080/api/v1/product/99/productId
# Testing "Getting a product with id is out of range" - Works correctly.
#{
#  "status": 404,
#  "message": "The Product with id=99 is not found!",
#  "timestamp": 1598768816567
#}

###

GET http://localhost:8080/api/v1/product/wrong_argument/productId
# testing a request with an illegal argument - Work correctly
#{
#  "status": 400,
#  "message": "Illegal Argument. Look that you write! For input string: \"wrong_argument\"",
#  "timestamp": 1598772359743
#}

###
# returns ResponseEntity<OutEntity>
GET http://localhost:8080/api/v1/product/2/productId
# getting a product by id - Works correctly!
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entity": "OutProduct",
#  "id": 2,
#  "categoryTitle": "Офисная техника",
#  "vendorCode": "00000002",
#  "title": "Pantum / Монохромный лазерный принтер P2207",
#  "price": 5095.00,
#  "shortDescription": "Монохромный лазерный принтер. Компактный дизайн, низкая стоимость печати и оригинальные заправочные комплекты.",
#  "fullDescription": "add full_description",
#  "createAt": "2020-08-19T08:06:15",
#  "updateAt": "2020-08-19T08:06:15"
#}