# For REST Resources testing

#******* Event **************
###
# HEROKU
#********* App for Developing Stage *********
###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/event/99/eventId
## testing not existing user by out of range id - Works correctly!
#{
#  "status": 404,
#  "message": "Event with id=99 is not found!",
#  "timestamp": 1599121018355
#}

###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/event/wrong_argument/eventId
# testing a request with an illegal argument - Work correctlly!
#{
#  "status": 400,
#  "message": "Illegal Argument. Look that you write! For input string: \"wrong_argument\"",
#  "timestamp": 1599216243804
#}

###

# returns ResponseEntity<OutEntity>
GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/event/serverUnaccepted/first
# getting the first server unaccepted event - Works correctly!
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Event",
#  "entityFields": {
#    "actionType": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "ActionType",
#      "entityFields": {
#        "entityType": "Order",
#        "description": "Изменился статус Заказа. Заказ переведен на следующий этап обработки",
#        "id": 2,
#        "title": "STATUS_CHANGED"
#      }
#    },
#    "createdAt": "2020-09-20T13:51:32",
#    "entityType": "Order",
#    "serverAcceptedAt": null,
#    "entityId": 3,
#    "id": 1
#  }
#}

# If None

#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Event",
#  "entityFields": {
#    "actionType": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "ActionType",
#      "entityFields": {
#        "entityType": "",
#        "description": "",
#        "id": 0,
#        "title": ""
#      }
#    },
#    "createdAt": "2020-09-20T13:50:44.677",
#    "entityType": "",
#    "serverAcceptedAt": "2020-09-20T13:50:44.678",
#    "entityId": 0,
#    "id": 0
#  }
#}

###
# returns ResponseEntity<OutEntity>
GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/event/1/eventId
# getting a event by id - Works correctly!.
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Event",
#  "entityFields": {
#    "actionType": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "ActionType",
#      "entityFields": {
#        "entityType": "Order",
#        "description": "Изменился статус Заказа. Заказ переведен на следующий этап обработки",
#        "id": 2,
#        "title": "STATUS_CHANGED"
#      }
#    },
#    "createdAt": "2020-09-20T13:51:32",
#    "entityType": "Order",
#    "serverAcceptedAt": null,
#    "entityId": 3,
#    "id": 1
#  }
#}

###

PUT https://dev-amin-ishop-heroku.herokuapp.com/api/v1/event/1/eventId/serverAcceptedAt/string

2020-09-11T09:46:32.773

###
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Event",
#  "entityFields": {
#    "actionType": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "ActionType",
#      "entityFields": {
#        "entityType": "Order",
#        "description": "Изменился статус Заказа. Заказ переведен на следующий этап обработки",
#        "id": 2,
#        "title": "STATUS_CHANGED"
#      }
#    },
#    "createdAt": "2020-09-20T13:51:32",
#    "entityType": "Order",
#    "serverAcceptedAt": "2020-09-11T09:46:32.773",
#    "entityId": 3,
#    "id": 1
#  }
#}
