# For REST Resources testing

#******* Order **************

GET http://localhost:8080/api/v1/order/99/orderId
# Testing "Getting a product with id is out of range" - Works correctly.
#{
#  "status": 404,
#  "message": "The Order with id=99 is not found!",
#  "timestamp": 1598786448626
#}

###

GET http://localhost:8080/api/v1/order/wrong_argument/orderId
# testing a request with an illegal argument - Work correctly
#{
#  "status": 400,
#  "message": "Illegal Argument. Look that you write! For input string: \"wrong_argument\"",
#  "timestamp": 1598793884529
#}

###
# returns ResponseEntity<OutEntity>
GET http://localhost:8080/api/v1/order/21/orderId
# getting a order by id - Works correctly!
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Order",
#  "entityFields": {
#    "delivery": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "Delivery",
#      "entityFields": {
#        "phoneNumber": "+79991234567",
#        "deliveryAddress": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityType": "Address",
#          "entityFields": {
#            "country": "Russia",
#            "address": "Секина 99, кв.99",
#            "city": "Королев МО",
#            "id": 3
#          }
#        },
#        "id": 1,
#        "deliveryExpectedAt": "2020-09-05T10:00:00",
#        "order": 2,
#        "deliveryCost": 100.00,
#        "deliveredAt": null
#      }
#    },
#    "createdAt": "2020-09-05T11:24:47",
#    "totalCosts": 3057.00,
#    "orderStatus": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "OrderStatus",
#      "entityFields": {
#        "description": "Доставлен: Заказ получен пользователем",
#        "id": 5,
#        "title": "Delivered"
#      }
#    },
#    "totalItemsCosts": 2957.00,
#    "id": 2,
#    "user": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "User",
#      "entityFields": {
#        "firstName": "f n liyuse",
#        "lastName": "l n liyuse",
#        "phoneNumber": "+79991234567",
#        "deliveryAddress": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityType": "Address",
#          "entityFields": {
#            "country": "Russia",
#            "address": "Секина 99, кв.99",
#            "city": "Королев МО",
#            "id": 3
#          }
#        },
#        "id": 2,
#        "userName": "liyuse",
#        "email": "liyuse@ yandex.ru"
#      }
#    },
#    "orderItems": [
#      {
#        "store": "gb-spring-amin-ishop-heroku",
#        "entityType": "OrderItem",
#        "entityFields": {
#          "itemCosts": 1958.00,
#          "product": {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityType": "Product",
#            "entityFields": {
#              "id": 9,
#              "shortDescription": 979.00,
#              "category": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityType": "Category",
#                "entityFields": {
#                  "id": 6,
#                  "title": "Книги"
#                }
#              },
#              "title": "Филипок и Ко / Скорочтение для детей от 6 до 9 лет.",
#              "fullDescription": "\"Скорочтение. Как научить ребенка быстро читать\" - переработанное и усовершенствованное переиздание успешного бестселлера по методике скорочтения Ахмадуллина, разделенное на две книги по возрасту для более точечной проработки навыков. Шамиль Ахмадуллин - психолог-педагог, физик, PhD, разработчик более 40 методик эффективного обучения детей. Основатель школ скорочтения и развития памяти у детей. За 18 дней 20-30 минутных занятий Ваш ребенок научится читать в 2 раза быстрее, лучше понимать, запоминать и пересказывать прочитанное. А главное - вы заложите в ребенка один из самых важных навыков 21 века - быстрое усвоение любой текстовой информации. Это даст ребенку огромные преимущества во взрослой жизни! Книга-тренинг для младших школьников: 18-дневный тренинг; более 100 заданий; улучшение внимания; повысится успеваемость в школе; ребенок научится пересказывать; тренировка памяти; формирование навыка быстрого чтения; занятия по 30 минут в день.",
#              "vendorCode": "00000009"
#            }
#          },
#          "quantity": 2,
#          "itemPrice": 979.00,
#          "id": 3,
#          "order": 2
#        }
#      },
#      {
#        "store": "gb-spring-amin-ishop-heroku",
#        "entityType": "OrderItem",
#        "entityFields": {
#          "itemCosts": 999.00,
#          "product": {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityType": "Product",
#            "entityFields": {
#              "id": 11,
#              "shortDescription": 999.00,
#              "category": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityType": "Category",
#                "entityFields": {
#                  "id": 5,
#                  "title": "Одежда"
#                }
#              },
#              "title": "ТВОЕ / Платье",
#              "fullDescription": "Размер на модели: S. *Параметры в описании указаны для размера: S.",
#              "vendorCode": "00000011"
#            }
#          },
#          "quantity": 1,
#          "itemPrice": 999.00,
#          "id": 4,
#          "order": 2
#        }
#      }
#    ],
#    "updatedAt": "2020-09-05T12:47:10"
#  }
#}

###
# returns ResponseEntity<OutEntity>
PUT http://localhost:8080/api/v1/order/21/orderId/changeOrderStatus/string

Accepted to work

###
# updatting a orderStatuse by title - Works correctly!
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "Order",
#  "entityFields": {
#    "delivery": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "Delivery",
#      "entityFields": {
#        "phoneNumber": "+79991234567",
#        "deliveryAddress": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityType": "Address",
#          "entityFields": {
#            "country": "Russia",
#            "address": "Секина 99, кв.99",
#            "city": "Королев МО",
#            "id": 3
#          }
#        },
#        "id": 19,
#        "deliveryExpectedAt": "2020-09-20T10:00:00",
#        "order": 21,
#        "deliveryCost": 100.00,
#        "deliveredAt": null
#      }
#    },
#    "createdAt": "2020-09-20T13:33:27",
#    "totalCosts": 2962.00,
#    "orderStatus": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "OrderStatus",
#      "entityFields": {
#        "description": "Принят в работу: Заказ обрабатывается",
#        "id": 2,
#        "title": "Accepted to work"
#      }
#    },
#    "totalItemsCosts": 2862.00,
#    "id": 21,
#    "user": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "User",
#      "entityFields": {
#        "firstName": "f n liyuse",
#        "lastName": "l n liyuse",
#        "phoneNumber": "+79991234567",
#        "deliveryAddress": {
#          "store": "gb-spring-amin-ishop-heroku",
#          "entityType": "Address",
#          "entityFields": {
#            "country": "Russia",
#            "address": "Секина 99, кв.99",
#            "city": "Королев МО",
#            "id": 3
#          }
#        },
#        "id": 2,
#        "userName": "liyuse",
#        "email": "liyuse@ yandex.ru"
#      }
#    },
#    "orderItems": [
#      {
#        "store": "gb-spring-amin-ishop-heroku",
#        "entityType": "OrderItem",
#        "entityFields": {
#          "itemCosts": 2862.00,
#          "product": {
#            "store": "gb-spring-amin-ishop-heroku",
#            "entityType": "Product",
#            "entityFields": {
#              "id": 5,
#              "shortDescription": 1431.00,
#              "category": {
#                "store": "gb-spring-amin-ishop-heroku",
#                "entityType": "Category",
#                "entityFields": {
#                  "id": 3,
#                  "title": "Бытовая техника"
#                }
#              },
#              "title": "Bosch / Кофемолка MKM 6000/6003",
#              "fullDescription": "Очень удобная в повседневной жизни кофемолка. Она предназначена для семей, которые любят выпить по утрам чашечку свежесваренного кофе. Производительность: до 75 гр. кофейных зерен. Степень помола зависит от его продолжительности: чем дольше, тем мельче. Мощность: 180 Вт. Лезвие из нержавеющей стали для точного и качественного помола. Помол осуществляется только при закрытой крышке.",
#              "vendorCode": "00000005"
#            }
#          },
#          "quantity": 2,
#          "itemPrice": 1431.00,
#          "id": 29,
#          "order": 21
#        }
#      }
#    ],
#    "updatedAt": "2020-09-20T13:35:02"
#  }
#}
