# For REST Resources testing

#******* Order **************
###
# HEROKU
#********* App for Developing Stage *********
###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/order/99/orderId
## testing not existing order by out of range id - Works correctly!
#

###

GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/order/wrong_argument/orderId
# testing a request with an illegal argument - Work correctlly!
#

###
# returns ResponseEntity<OutEntity>
GET https://dev-amin-ishop-heroku.herokuapp.com/api/v1/order/1/orderId
# getting a order by id - Works correctly!
#