# For REST Resources testing

#******* User **************

GET http://localhost:8080/api/v1/user/99/userId
# Testing "Getting a product with id is out of range" - Works correctly.
#{
#  "status": 404,
#  "message": "The User with id=99 is not found!",
#  "timestamp": 1598793868634
#}

###

GET http://localhost:8080/api/v1/user/wrong_argument/userId
# testing a request with an illegal argument - Work correctly
#{
#  "status": 400,
#  "message": "Illegal Argument. Look that you write! For input string: \"wrong_argument\"",
#  "timestamp": 1598793884529
#}

###
# returns ResponseEntity<OutEntity>
GET http://localhost:8080/api/v1/user/1/userId
# getting a user by id - Works correctly!
#{
#  "store": "gb-spring-amin-ishop-heroku",
#  "entityType": "User",
#  "entityFields": {
#    "firstName": "superadmin first_name",
#    "lastName": "superadmin last_name",
#    "phoneNumber": "+79991234567",
#    "deliveryAddress": {
#      "store": "gb-spring-amin-ishop-heroku",
#      "entityType": "Address",
#      "entityFields": {
#        "country": "USA",
#        "address": "18a Diagon Alley",
#        "city": "New York",
#        "id": 1
#      }
#    },
#    "id": 1,
#    "userName": "superadmin",
#    "email": "superadmin@ mail.com"
#  }
#}

###